# Generated by Django 6.0 on 2025-12-15 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=20, verbose_name='телефон')),
                ('organisation', models.CharField(blank=True, max_length=100, verbose_name='Организация')),
                ('note', models.TextField(blank=True, verbose_name='заметки')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='название')),
                ('datetime', models.DateTimeField(verbose_name='Дата и время')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
            ],
        ),
    ]
